packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@ai-sdk/anthropic': ^3.0.1
  '@ai-sdk/google': ^3.0.1
  '@ai-sdk/openai': ^3.0.1
  '@ai-sdk/xai': ^3.0.1
  '@types/lodash': ^4.17.21
  ai: ^6.0.3
  dexie: ^4.2.1
  html-entities: ^2.6.0
  json5: ^2.2.3
  lodash: ^4.17.21
  marked: ^17.0.1
  tsdown: ^0.17.4
  vite: ^7.3.0
  zod: ^4.2.1

catalogMode: prefer

catalogs:
  cli:
    '@antfu/eslint-config': ^6.6.1
    '@antfu/ni': ^28.0.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    publint: ^0.3.16
    simple-git-hooks: ^2.13.1
    tsdown: ^0.17.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.2.7
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.15
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.1

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true

trustPolicy: no-downgrade
